name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  issues: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore AVB_Windows.sln

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build solution
      run: |
        msbuild AVB_Windows.sln /p:Configuration=Release
        # Ensure build.log is created during the build process
        if [ ! -f build.log ]; then
          echo "Build log not found. Creating build.log."
          touch build.log
        fi

    - name: Run Unit Tests
      run: |
        vstest.console.exe Path\To\Your\TestProject.dll

    - name: Run PVS-Studio Analysis
      run: |
        # Install PVS-Studio
        choco install pvs-studio

        # Run analysis
        "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" \
          --target "AVB_Windows.sln" \
          --configuration "Release" \
          --output "PVS-Studio.log"

    - name: Check Code Formatting
      run: |
        choco install llvm

        clang-format -i -style=file **/*.cpp **/*.h

        git diff --exit-code

    - name: Download Intel Tools
      run: |
        curl -o Intel_Ethernet_Controller_I210_Datasheet.pdf https://www.intel.com/content/www/us/en/products/sku/58954/intel-ethernet-controller-i210at/specifications.html
        curl -o Intel_Ethernet_Adapter_Complete_Driver_Pack.zip https://downloadcenter.intel.com/product/36773/Intel-Ethernet-Adapters
        curl -o Intel_System_Studio.exe https://www.intel.com/content/www/us/en/developer/tools/system-studio/overview.html
        curl -o Intel_VTune_Profiler.exe https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html

    - name: Run Intel Tools
      run: |
        # Run Intel System Studio
        start /wait Intel_System_Studio.exe /S

        # Run Intel VTune Profiler
        start /wait Intel_VTune_Profiler.exe /S

    - name: Validate AVB Implementation
      run: |
        # Run validation scripts using Intel tools
        python validate_avb.py

    - name: Update SRS
      run: |
        # Update the SRS document with new requirements
        python update_srs.py

    - name: Update Documentation
      run: |
        # Update the documentation with new requirements and considerations
        python update_docs.py

    - name: Update README
      run: |
        # Update the README with new requirements and key insights
        python update_readme.py

    - name: Run Error Detection
      run: |
        python scripts/error_detection.py

    - name: Save Errors and Metadata
      run: |
        python scripts/error_detection.py > errors_and_metadata.json

    - name: Install PyGithub
      run: pip install PyGithub

    - name: Upload Build Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: build.log

    - name: Check for Missing Logs
      run: |
        if [ ! -f build.log ]; then
          echo "No logs found. Skipping error-checking step."
        fi

    - name: Run Issue Creation
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_SHA: ${{ github.sha }}
        BUILD_LOGS_LINK: ${{ steps.upload_build_logs.outputs.url }}
      run: |
        python scripts/issue_creation.py
